### PR TITLE
add cube

### PR DESCRIPTION
**Pull request by legitimatetheory5476**
### Before
Screenshot 2021-04-25 at 10 07 30 am

### After
Screenshot 2021-04-25 at 10 08 14 am

### CODE REVIEW

**Comment by daggy1234** [comment]
Looks like a great command. Just very similar too https://github.com/linKhehe/ZaneAPI/blob/rewrite/zaneapi/blueprints/api.py#L243-L274. Just curious.

**Comment by legitimatetheory5476** [comment]
I can assure you I did not copy the mentioned link’s code. Moreover, there are thousands of lines of similar code across the internet, which I put together.

**Comment by daggy1234** [comment]
Alrighty then this looks good to me, just rebase/resolve conflicts and I'll merge!

**Comment by legitimatetheory5476** [comment]
Resolved conflicts.

**Comment by daggy1234** [comment]
Cools

**Pull request merged**
