### PR TITLE
Add detail/smooth/blur

### PR DESCRIPTION
**Pull request by z03h**
Adds a slightly weaker sharpen with `ImageFilter.DETAIL` for 0, other sharpen options moved up
Adds option to smooth/smooth more/gaussian blur image before getting outlines as -1, -2, and -3 or below

### CODE REVIEW

**Comment by z03h** [comment]
editing this on github so every time I merge commits from upstream it keeps adding more commits 🤔 
too dented to figure this out

**Comment by daggy1234** [comment]
lol

**Comment by daggy1234** [comment]
@z03h is this ready to merge?

**Comment by daggy1234** [comment]
Ty Zoot!

**Pull request merged**
